spring.application.name=case-tecnico
server.port=8080

hubspot.redirect-uri=http://localhost:8080/authorization/oauth-callback
hubspot.authorize-uri=https://app.hubspot.com/oauth/authorize
hubspot.api-url=https://api.hubapi.com/crm/v3/objects/

hubspot.client-id=1b8c10c0-9209-4c89-b5c9-2f36be3d96e6
hubspot.client-secret=6c4590f1-4a41-462a-a8c5-66dd830d05b8
hubspot.scope=crm.objects.contacts.write crm.objects.contacts.read
