spring.application.name=case-tecnico
server.port=8080

hubspot.client-id=1b8c10c0-9209-4c89-b5c9-2f36be3d96e6
hubspot.client-secret=6c4590f1-4a41-462a-a8c5-66dd830d05b8
hubspot.redirect-uri=http://localhost:8080/authorization/oauth-callback
hubspot.optional_scope=
hubspot.state=